---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: generate
    image: docker.io/owncloudci/alpine
    commands:
      - make

- name: publish
  image: quay.io/thegeeklab/drone-git-action
  settings:
    action:
      - commit
      - push
    author_email: devops@owncloud.com
    author_name: ownclouders
    branch: main
    message: "[skip ci] automated blacklists update"
    netrc_password:
      from_secret: github_token
  when:
    ref:
      - refs/heads/main

trigger:
  ref:
    - refs/heads/main
    - refs/pull/**
